# Generated by Django 5.2.5 on 2025-08-15 14:50

import accounts.models.users
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(help_text="权限唯一标识符，如 'view_dashboard', 'export_data'", max_length=100, unique=True)),
                ('name', models.CharField(help_text="权限名称，如 '查看仪表盘', '导出数据'", max_length=255)),
                ('description', models.TextField(blank=True, help_text='权限描述')),
                ('app_label', models.CharField(blank=True, db_index=True, help_text="所属应用或模块，如 'reports', 'admin'", max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': '自定义权限',
                'verbose_name_plural': '自定义权限',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('codename',), name='unique_active_codename')],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="角色名称，如 '管理员', '分析师'", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='角色描述')),
                ('is_system', models.BooleanField(default=False, help_text='系统内置角色，通常不可删除或修改')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.ManyToManyField(blank=True, help_text='该角色拥有的权限', related_name='roles', to='accounts.custompermission')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=accounts.models.users.upload_to)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='角色有效期，为空表示永久有效', null=True)),
                ('notes', models.TextField(blank=True, help_text='备注')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='分配此角色的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_user_roles', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='accounts.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户角色',
                'verbose_name_plural': '用户角色',
                'unique_together': {('user', 'role')},
            },
        ),
    ]
